version: '3'

volumes:
  peer0.org2.ap.com:
networks:
  apnet:

services:
  peer0.org2.ap.com:
    networks:
      - apnet   
    container_name: peer0.org2.ap.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlf_tracker_apnet
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.ap.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052

      # Generic peer variables
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Specific peer variables
      - CORE_PEER_ID=peer0.org2.ap.com
      - CORE_PEER_ADDRESS=peer0.org2.ap.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.ap.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.ap.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/data/crypto-material/peerOrganizations/org2.ap.com/users/Admin@org2.ap.com/msp/
    volumes:
        - ../:/data
        - /var/run/:/host/var/run/
        - ../crypto-material/peerOrganizations/org2.ap.com/peers/peer0.org2.ap.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-material/peerOrganizations/org2.ap.com/peers/peer0.org2.ap.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.ap.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
      