version: "3"

volumes:
  peer0.org1.ap.com:
  ca.org1.ap.com:

networks:
  apnet:

services:
  ca.org1.ap.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.ap.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.ap.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.ap.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw'

    volumes:
      - ca.org1.ap.com:/etc/hyperledger/fabric-ca-server
      - ../crypto-material/peerOrganizations/org1.ap.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.ap.com
    networks:
      - apnet

  peer0.org1.ap.com:
    networks:
      - apnet
    container_name: peer0.org1.ap.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-material/peerOrganizations/org1.ap.com/peers/peer0.org1.ap.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-material/peerOrganizations/org1.ap.com/peers/peer0.org1.ap.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.ap.com:/var/hyperledger/production
      - ../:/data
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlf_tracker_apnet
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.ap.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Generic peer variables
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt 
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key 
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt 
      # Specific peer variables
      - CORE_PEER_ID=peer0.org1.ap.com
      - CORE_PEER_ADDRESS=peer0.org1.ap.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.ap.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.ap.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/data/crypto-material/peerOrganizations/org1.ap.com/users/Admin@org1.ap.com/msp/
      #- FABRIC_CFG_PATH=/data/config/

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051